# Generated by Django 4.2.4 on 2023-09-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='App',
        ),
    ]
