# Generated by Django 4.2.4 on 2023-09-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0002_rename_teacher_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='App',
        ),
    ]
