# Generated by Django 4.2.4 on 2023-09-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0003_teacher_delete_app'),
    ]

    operations = [
    ]
