# Generated by Django 4.2.4 on 2023-09-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0004_auto_20230903_0126'),
    ]

    operations = [
    ]
